language: python
install:
  - pip install -r requirements.txt
services:
  - postgresql
env:
  global:
    - PGPORT=5433
    - FLASK_APP="run.py"
    - APP_SETTINGS="development"
    - FLASK_ENV=$APP_SETTINGS
    - PGPORT=5433
    - DATABASE_URL="postgresql://localhost:5433/test"
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
script:
  - python manage.py test
