language: python
python:
  - 3.8
dist: trusty
env:
  global:
    - APP_SETTINGS="test"
    - FLASK_ENV=$APP_SETTINGS
install:
  - pip install -r requirements.txt
script:
  - coverage erase
  - coverage run manage.py test
  - coverage report -m 
